services:
  - type: web
    name: centerflex-api
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: ADMIN_USER
        value: admin
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://oxpvfaisvhzndesdjjzc.supabase.co
      - key: SUPABASE_KEY
        sync: false